#! /usr/bin/env python
# vim : set fileencoding=utf-8 expandtab noai ts=4 sw=4 filetype=python :
top = '..'

def build(self):
  self.recurse_all()
  self.recurse_all_tests()
  self(
        target       = 'sr_sif',
        features     = 'cxx cxxshlib',
        source = ['Sif.cpp', 'SfrProgrammer.cpp'] + self.path.ant_glob('memory/*.cpp'),
        includes = self.top_dir,
        defines = 'ENABLE_HISTORY', 
        use          = ['trap', 'sr_registry', 'sr_register', 'sr_report', 'sr_signal', 'common', 'TLM', 'SYSTEMC', 'BOOST',
		'TLMSOCKET'],
        idx=199,
  )
